# Generated by Django 5.1.4 on 2024-12-19 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('image_srcs', models.JSONField(default=list)),
                ('sizes', models.JSONField(default=list)),
            ],
        ),
    ]
